Repository QuEST-Kit/QuEST, pull requests merged in 2019-10, with the labels that each got.

#175 Fix #174 for Python 3.4
  utilities/QuESTTest/QuESTCore.py
Labels: bug

#169 Refactoring complex matrix
  AUTHORS.txt
  QuEST/include/QuEST.h
  QuEST/src/CPU/QuEST_cpu.c
  QuEST/src/CPU/QuEST_cpu_distributed.c
  QuEST/src/CPU/QuEST_cpu_internal.h
  QuEST/src/CPU/QuEST_cpu_local.c
  QuEST/src/GPU/QuEST_gpu.cu
  QuEST/src/QuEST.c
  QuEST/src/QuEST_common.c
  QuEST/src/QuEST_internal.h
  QuEST/src/QuEST_validation.c
  QuEST/src/QuEST_validation.h
  QuEST/src/mainpage.h
  README.md
  examples/README.md
  examples/damping_example.c
  examples/tutorial_circuit.png
  examples/tutorial_example.c
  tests/unit/density_matrix/noise/applyOneQubitDampingError.test
  tests/unit/density_matrix/noise/applyOneQubitDephaseError.test
  tests/unit/density_matrix/noise/applyOneQubitDepolariseError.test
  tests/unit/density_matrix/noise/applyTwoQubitDephaseError.test
  tests/unit/density_matrix/noise/applyTwoQubitDepolariseError.test
  tutorial_example.c
  utilities/QuESTPy/QuESTFunc.py
Labels: enhancement

#179 Improving doc
  AUTHORS.txt
  CMakeLists.txt
  QuEST/include/QuEST.h
  QuEST/include/QuEST_complex.h
  QuEST/include/QuEST_precision.h
  QuEST/src/CPU/QuEST_cpu.c
  QuEST/src/CPU/QuEST_cpu_distributed.c
  QuEST/src/CPU/QuEST_cpu_internal.h
  QuEST/src/CPU/QuEST_cpu_local.c
  QuEST/src/GPU/QuEST_gpu.cu
  QuEST/src/QuEST.c
  QuEST/src/QuEST_common.c
  QuEST/src/QuEST_debug.h
  QuEST/src/QuEST_internal.h
  QuEST/src/QuEST_qasm.c
  QuEST/src/QuEST_qasm.h
  QuEST/src/QuEST_validation.c
  QuEST/src/QuEST_validation.h
  QuEST/src/mainpage.h
  doxyconf
  examples/bernstein_vazirani_circuit.c
  examples/damping_example.c
  examples/makefile
  examples/tutorial_example.c
  tests/algor/QFT.test
  tests/algor/rotate_test.test
  tests/benchmarks/rotate_benchmark.test
  tests/essential/state_vector/createDensityQureg.test
  tests/essential/state_vector/createQureg.test
  tests/essential/state_vector/destroyQureg.test
  tests/essential/state_vector/seedQuEST.test
  tests/unit/state_vector/maths/calcFidelity.test
  tests/unit/state_vector/maths/calcInnerProduct.test
  tests/unit/state_vector/maths/measure.test
  tests/unit/state_vector/maths/measureWithStats.test
Labels: documentation

#177 Added Hilbert-Schmidt scalar product (CPU)
  CMakeLists.txt
  QuEST/include/QuEST.h
  QuEST/src/CPU/QuEST_cpu.c
  QuEST/src/CPU/QuEST_cpu_distributed.c
  QuEST/src/CPU/QuEST_cpu_internal.h
  QuEST/src/CPU/QuEST_cpu_local.c
  QuEST/src/QuEST.c
  QuEST/src/QuEST_internal.h
  README.md
Labels: enhancement

#182 included (hardware agnostic) copyStateToGPU in API
  QuEST/include/QuEST.h
  QuEST/src/CPU/QuEST_cpu.c
  QuEST/src/GPU/QuEST_gpu.cu
  QuEST/src/QuEST.c
  tests/algor/rotate_test.test
  tests/essential/state_vector/initDebugState.test
  utilities/QuESTPy/QuESTFunc.py
Labels: enhancement

#185 Hilbert-Schmidt scalar product of density matrices (GPU)
  QuEST/include/QuEST.h
  QuEST/src/GPU/QuEST_gpu.cu
Labels: enhancement
